### ISSUE TITLE
USB card reader

### ISSUE THREAD

**Issue by tomkukral** [techSU/kati#1]
What do you think about using different card readers?
USB card readers are used at CTU FIT and it would solve all of the problems with reading GPIO, interrupts and concurency. 

cc @PavelTrutman @tomasbedrich

**Comment by ah01** [comment]
Do you have any details for reader used by CTU FIT? Manufacturer, type, etc.

Most readers I saw are using serial or wiegand interface. And those with USB interface (typically desktop reader for client registration) not fulfil requirements by ČSN EN 50133-2-1.

**Comment by PavelTrutman** [comment]
@tomasbedrich Do you think you will make the GPIO/Wiegand approach work?

If this fails the USB card readers will be solution. But it will cause other problems, e.g. that the card readers will have to be powered by the RPi.

**Comment by tomasbedrich** [comment]
Yes, I think it will be OK.

Another option would be to use some ATMega to read a Wiegand data and transfer the card ID using serial line – maybe I would prefer this solution because the Raspberry wouldn't have to care about precise timing, which is not ideal for.

**Comment by tomasbedrich** [comment]
Closing this issue, because we made the Wiegand working. 🎉
